config/routes.rb
TheSurf::Application.routes.draw do
  resources :articles, :only => [ :index, :show, :create, :update, :destroy ]

  match 'archive(.:format)', :to => 'articles#archive', :as => :archive

  match ':id', :to => 'articles#show'

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  scope :ordered, order('published_at DESC')
  validates_presence_of :title, :slug, :content, :summary, :published_at
  validates_uniqueness_of :slug

  def content_html
    render_markdown(content)
  end

  def summary_html
    render_markdown(summary)
  end

  def to_param
    slug
  end

  private

  def render_markdown(str)
    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, 
      :fenced_code_blocks => true, :hard_wrap => true)
    renderer.render(str)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :set_layout
  protect_from_forgery

  protected

  def authorized?
    authenticate_with_http_basic do |username, password|
      password == App.http_auth_key
    end
  end

  def authorized!
    head(401) unless authorized?
  end

  def pjax?
    request.headers['X-PJAX'] ? true : false
  end

  private

  def set_layout
    if pjax?
      false
    else
      "application"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorized!, :except => [ :index, :show, :archive ]
  cache_sweeper :article_sweeper
  caches_action :index, :archive, :cache_path => Proc.new { |c|
    "/#{c.controller_path}/#{c.action_name}.#{c.request.format}#{c.pjax? ? "/pjax" : ""}"
  }
  caches_action :show, :cache_path => Proc.new { |c|
    "/#{c.controller_path}/#{c.action_name}/#{c.params[:id]}.#{c.request.format}#{c.pjax? ? "/pjax" : ""}"
  }
  
  def index
    respond_to do |format|
      format.atom { @articles = Article.ordered.limit(20) }
      format.html { @article = Article.ordered.first }
      format.json { render json: Article.ordered.limit(20) }
    end
  end

  def show
    @article = Article.find_by_slug!(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @article }
    end
  end

  def archive
    @articles = Article.ordered.group_by{ |a| a.published_at.year }.sort.reverse

    respond_to do |format|
      format.html
      format.json { render json: @articles }
    end
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.json { render json: @article, status: :created, location: @article }
      else
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find_by_slug!(params[:id])

    respond_to do |format|
      if @article.update_attributes(article_params)
        format.json { head :no_content }
      else
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find_by_slug!(params[:id])
    @article.destroy

    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def article_params
    if params[:attributes] && params[:content]
      attributes = eval(params[:attributes])
      attributes[:content] = params[:content]
    else
      attributes = params[:article]
    end
    attributes.slice(:title, :slug, :summary, :content, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def article_path(article)
    "/#{article.slug}"
  end

  def pjax?
    request.headers['X-PJAX']
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.slim
.row
  .col_12.last
    article
      h1= @article.title
      == @article.content_html
      p.extra
        | Published #{@article.published_at.strftime("%B %d, %Y")}. #{link_to 'Permalink', @article, "data-pjax" => "#content"}.

app/views/articles/_other_articles.html.slim
- if Article.count > 1
  #other_articles
    .row
      .col_12.last
        h2 Other Articles
        ul
          - Article.ordered.limit(3).where("id <> ?", @article.id).each do |article|
            li
              p= link_to article.title, article, "data-pjax" => "#content"
              .summary
                p== article.summary_html
        p= link_to "All other articles. &rarr;".html_safe, archive_path, "data-pjax" => "#content"

app/views/articles/_siblings.html.slim
- prev_article = Article.ordered.where("published_at < ?", @article.published_at).first
- next_article = Article.ordered.where("published_at > ?", @article.published_at).last
- if prev_article || next_article
  #siblings
    .row
      #prev.col_6
        - if prev_article
          = link_to raw("&larr; #{prev_article.title}"), prev_article, "data-pjax" => "#content"
        - else
          | &nbsp;
      #next.col_6.last
        - if next_article
          = link_to raw("#{next_article.title} &rarr;"), next_article, "data-pjax" => "#content"
        - else
          | &nbsp;

app/views/articles/archive.html.slim
- content_for :title, "Archive"
- if pjax?
  title Archive
#archive
  .row
    .col_12.last
      h1 Archive
      - @articles.each do |year, articles|
        - if year != Date.today.year
          h2= year
        ul
          - articles.each do |article|
            li
              = link_to article.title, article, "data-pjax" => "#content"
              |  
              span.extra= article.published_at.strftime("%b %d")

app/views/articles/index.html.slim
- if @article
  - if pjax?
    title The Surf
  = render partial: "article"
  = render partial: "siblings"
  = render partial: "other_articles"

app/views/articles/show.html.slim
- content_for :title, @article.title
- if pjax?
  title= @article.title
= render partial: "article"
= render partial: "siblings"
= render partial: "other_articles"

app/views/layouts/application.html.slim
doctype 5

html lang='en'
  head
    title= content_for?(:title) ? yield(:title) : 'The Surf'

    meta content='text/html; charset=utf-8' http-equiv='Content-Type'
    meta name='author' content='Brandur Leach'

    link rel='icon' type='image/png' href='/images/icon.png'
    link rel='shortcut icon' type='image/png' href='/images/icon.png'
    link href='/articles.atom' rel='alternate' title="The Surf" type='application/atom+xml'
    
    link href='http://fonts.googleapis.com/css?family=Playfair+Display|EB+Garamond' rel='stylesheet' type='text/css'

    = stylesheet_link_tag    'application', :debug => Rails.env.development?
    = javascript_include_tag 'application', :debug => Rails.env.development?

    = csrf_meta_tag

    / Enable HTML5 styling for the bane of the Internet
    /[ if lt IE 9 ]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

    = yield(:head)

  body
    #wrapper
      header
        .row
          .col_12.last
            #title
              = link_to 'the surf ', '/', "data-pjax" => "#content"
              span.wave &
      #content
        = yield
      nav
      footer
        .row
          .col_12.last
            | Written by #{link_to "Brandur Leach", "http://brandur.org"}. This Surf's journal engine is #{link_to "open source", "https://github.com/brandur/the-surf"}.